[tool.poetry]
name = "tiralabra-luolastogeneraattori"
version = "0.1.0"
description = ""
authors = ["Jussi Rantala <jussi.v.rantala@helsinki.fi>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pylint = "^2.13.5"
coverage = "^6.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
